work_dir: ./work_dir/ntu/xview/agcn_fusion_test
model_saved_name: ./runs/ntu_cv_agcn_fusion_test
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  bone_path: ./data/ntu/xview/train_data_bone.npy
  joint_path: ./data/ntu/xview/train_data_joint.npy
  label_path: ./data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  bone_path: ./data/ntu/xview/val_data_bone.npy
  joint_path: ./data/ntu/xview/val_data_joint.npy
  label_path: ./data/ntu/xview/val_label.pkl

# model
model: model.agcn.FusionModel
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0,1]
batch_size: 16
test_batch_size: 16
num_epoch: 50
nesterov: True
