work_dir: ./work_dir/ntu120/xsub/agcn_joint_sw
model_saved_name: ./runs/ntu120_cs_agcn_joint_sw
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/NTU-RGB-D_120/xsub-1/train_data.npy
  label_path: ./data/NTU-RGB-D_120/xsub-1/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/NTU-RGB-D_120/xsub-1/val_data.npy
  label_path: ./data/NTU-RGB-D_120/xsub-1/val_label.pkl

# model
model: model.agcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
weights: ./runs/ntu120_cs_agcn_joint_sw-29-67620.pt
start_epoch: 30
device: [0, 1]
batch_size: 28
test_batch_size: 28
num_epoch: 50
nesterov: True

